// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLlB_H60Ebu3zvK0P1ZuWpXip37NnqvF8',
    appId: '1:897008008496:web:f559d2e33d4c09c5555cf5',
    messagingSenderId: '897008008496',
    projectId: 'streamify-firebase',
    authDomain: 'streamify-firebase.firebaseapp.com',
    storageBucket: 'streamify-firebase.firebasestorage.app',
    measurementId: 'G-TGBJ6XLSQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoivERlqJkO8p4IK-PWrYtIwTv-fHSo9o',
    appId: '1:897008008496:android:658f5831ba99718b555cf5',
    messagingSenderId: '897008008496',
    projectId: 'streamify-firebase',
    storageBucket: 'streamify-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhb2XJsT4ThtcvVT1K2tyYPyxLmMmyV5Y',
    appId: '1:897008008496:ios:653d2026fbb086a0555cf5',
    messagingSenderId: '897008008496',
    projectId: 'streamify-firebase',
    storageBucket: 'streamify-firebase.firebasestorage.app',
    iosBundleId: 'com.example.streamify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhb2XJsT4ThtcvVT1K2tyYPyxLmMmyV5Y',
    appId: '1:897008008496:ios:653d2026fbb086a0555cf5',
    messagingSenderId: '897008008496',
    projectId: 'streamify-firebase',
    storageBucket: 'streamify-firebase.firebasestorage.app',
    iosBundleId: 'com.example.streamify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLlB_H60Ebu3zvK0P1ZuWpXip37NnqvF8',
    appId: '1:897008008496:web:58b9780638e98869555cf5',
    messagingSenderId: '897008008496',
    projectId: 'streamify-firebase',
    authDomain: 'streamify-firebase.firebaseapp.com',
    storageBucket: 'streamify-firebase.firebasestorage.app',
    measurementId: 'G-LEFG60JCGQ',
  );
}
